### ISSUE TITLE
Remove subscription versioning based on assembly version

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/NServiceBus.Persistence.MongoDb#18]
We've recently concluded that including the major version of the assembly containing the message contracts could lead to message loss for users not aware of this behavior. NServiceBus core 5.2.17 was released to fix this https://github.com/Particular/NServiceBus/pull/4177.

Looking at the code I think the same problem exists here. It seems to [filter on the `Major` version part](https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/blob/master/src/NServiceBus.Persistence.MongoDb/Subscriptions/SubscriptionPersister.cs#L38)?

I have a hunch that just removing that part isn't enough since [the stored ID contains](https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/blob/master/src/NServiceBus.Persistence.MongoDb/Subscriptions/Subscription.cs#L14) the typename and the major part?

**Comment by tekmaven** [comment]
This is going to require a schema change, as you've identified.  I'd like to tackle this in the next release.

**Comment by timbussmann** [comment]
Since this repository is no longer maintained, we are closing this issue. We recommend to use the [officially supported NServiceBus.Storage.MongoDB package](https://github.com/Particular/NServiceBus.Storage.MongoDB) and re-open the issue/PR there if it still applies.
