### ISSUE TITLE
Add Outbox support

### ISSUE THREAD

**Issue by mattwhetton** [ParticularLabs/NServiceBus.Persistence.MongoDb#19]
Outbox is a feature of NServiceBus which higher l;evel of reliability with regard to processing messages exactly once (in non-dtc environments). 

The feature requires persistence and as such would be a great addition to this package.

[https://docs.particular.net/nservicebus/outbox/](https://docs.particular.net/nservicebus/outbox/)

**Comment by danielmarbach** [comment]
@tekmaven do you have any plans to implement this? Maybe looking into how it is done here https://github.com/Particular/NServiceBus.RavenDB/tree/develop/src/NServiceBus.RavenDB/Outbox could help

**Comment by buvinghausen** [comment]
Guys outbox support on MongoDB is not available because they do not support cross document transactions. The reason it is supported in RavenDB is because Raven does support cross document transactions.

**Comment by buvinghausen** [comment]
With Mongo 4.0 supporting transactions across multiple operations Outbox will now be possible.  I'm afraid this GitHub repository has become a tombstone however...

**Comment by timbussmann** [comment]
Hey @mattwhetton,
We're closing this issue as this repository is no longer actively maintained. We have implemented Outbox support on the [officially supported MongoDB persistence](https://github.com/Particular/NServiceBus.Storage.MongoDB) 🎉

**Comment by buvinghausen** [comment]
Thank you @timbussmann
