### ISSUE TITLE
Subscription storage in V5 is case sensitive

### ISSUE THREAD

**Issue by mauroservienti** [ParticularLabs/NServiceBus.Persistence.MongoDb#22]
The MongoDB subscription storage might be affected by a bug due to the usage of `Address.ToString()` when adding new subscriptions.

At [`Subscribe`](https://github.com/tekmaven/NServiceBus.Persistence.MongoDb/blob/v5/src/NServiceBus.Persistence.MongoDb/Subscriptions/SubscriptionPersister.cs#L30) time `client.ToString()` is used to render the subscriber address. in NServiceBus V5 [`Address.ToString()`](https://github.com/Particular/NServiceBus/blob/5.2.21/src/NServiceBus.Core/Address.cs#L186) is case sensitive.

This might result in a scenario, if I understood correctly how the persister works, where a subscription request from `a@B` and one from `a@b` end up in 2 different subscriptions causing duplicate events to be published at the same subscriber.

Is the described scenario possible?

**Comment by timbussmann** [comment]
Since this repository is no longer maintained, we are closing this issue. We recommend to use the [officially supported NServiceBus.Storage.MongoDB package](https://github.com/Particular/NServiceBus.Storage.MongoDB) and re-open the issue/PR there if it still applies.
